#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFFiles
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Navigator2013")]
	public partial class DataClassesFilesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertComptroller_File_Attachment(Comptroller_File_Attachment instance);
    partial void UpdateComptroller_File_Attachment(Comptroller_File_Attachment instance);
    partial void DeleteComptroller_File_Attachment(Comptroller_File_Attachment instance);
    partial void InsertComptroller_Change_Log_Entry(Comptroller_Change_Log_Entry instance);
    partial void UpdateComptroller_Change_Log_Entry(Comptroller_Change_Log_Entry instance);
    partial void DeleteComptroller_Change_Log_Entry(Comptroller_Change_Log_Entry instance);
    #endregion
		
		public DataClassesFilesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Navigator2013ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFilesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFilesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFilesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFilesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Comptroller_File_Attachment> Comptroller_File_Attachments
		{
			get
			{
				return this.GetTable<Comptroller_File_Attachment>();
			}
		}
		
		public System.Data.Linq.Table<Comptroller_Change_Log_Entry> Comptroller_Change_Log_Entries
		{
			get
			{
				return this.GetTable<Comptroller_Change_Log_Entry>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Comptroller$File Attachment]")]
	public partial class Comptroller_File_Attachment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Data.Linq.Binary _timestamp;
		
		private int _Table_ID;
		
		private string _Primary_Key_Value_1;
		
		private string _Primary_Key_Value_2;
		
		private string _Primary_Key_Value_3;
		
		private string _No_;
		
		private string _Description;
		
		private System.Data.Linq.Binary _Attachment;
		
		private string _No__Series;
		
		private string _FileName;
		
		private string _Created_By;
		
		private System.DateTime _Date_Created;
		
		private System.DateTime _Last_Modified;
		
		private string _Last_Modified_By;
		
		private byte _Transferred_to_Dest_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntimestampChanging(System.Data.Linq.Binary value);
    partial void OntimestampChanged();
    partial void OnTable_IDChanging(int value);
    partial void OnTable_IDChanged();
    partial void OnPrimary_Key_Value_1Changing(string value);
    partial void OnPrimary_Key_Value_1Changed();
    partial void OnPrimary_Key_Value_2Changing(string value);
    partial void OnPrimary_Key_Value_2Changed();
    partial void OnPrimary_Key_Value_3Changing(string value);
    partial void OnPrimary_Key_Value_3Changed();
    partial void OnNo_Changing(string value);
    partial void OnNo_Changed();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAttachmentChanging(System.Data.Linq.Binary value);
    partial void OnAttachmentChanged();
    partial void OnNo__SeriesChanging(string value);
    partial void OnNo__SeriesChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnCreated_ByChanging(string value);
    partial void OnCreated_ByChanged();
    partial void OnDate_CreatedChanging(System.DateTime value);
    partial void OnDate_CreatedChanged();
    partial void OnLast_ModifiedChanging(System.DateTime value);
    partial void OnLast_ModifiedChanged();
    partial void OnLast_Modified_ByChanging(string value);
    partial void OnLast_Modified_ByChanged();
    partial void OnTransferred_to_Dest_Changing(byte value);
    partial void OnTransferred_to_Dest_Changed();
    #endregion
		
		public Comptroller_File_Attachment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Table ID]", Storage="_Table_ID", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int Table_ID
		{
			get
			{
				return this._Table_ID;
			}
			set
			{
				if ((this._Table_ID != value))
				{
					this.OnTable_IDChanging(value);
					this.SendPropertyChanging();
					this._Table_ID = value;
					this.SendPropertyChanged("Table_ID");
					this.OnTable_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key Value 1]", Storage="_Primary_Key_Value_1", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string Primary_Key_Value_1
		{
			get
			{
				return this._Primary_Key_Value_1;
			}
			set
			{
				if ((this._Primary_Key_Value_1 != value))
				{
					this.OnPrimary_Key_Value_1Changing(value);
					this.SendPropertyChanging();
					this._Primary_Key_Value_1 = value;
					this.SendPropertyChanged("Primary_Key_Value_1");
					this.OnPrimary_Key_Value_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key Value 2]", Storage="_Primary_Key_Value_2", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string Primary_Key_Value_2
		{
			get
			{
				return this._Primary_Key_Value_2;
			}
			set
			{
				if ((this._Primary_Key_Value_2 != value))
				{
					this.OnPrimary_Key_Value_2Changing(value);
					this.SendPropertyChanging();
					this._Primary_Key_Value_2 = value;
					this.SendPropertyChanged("Primary_Key_Value_2");
					this.OnPrimary_Key_Value_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key Value 3]", Storage="_Primary_Key_Value_3", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string Primary_Key_Value_3
		{
			get
			{
				return this._Primary_Key_Value_3;
			}
			set
			{
				if ((this._Primary_Key_Value_3 != value))
				{
					this.OnPrimary_Key_Value_3Changing(value);
					this.SendPropertyChanging();
					this._Primary_Key_Value_3 = value;
					this.SendPropertyChanged("Primary_Key_Value_3");
					this.OnPrimary_Key_Value_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string No_
		{
			get
			{
				return this._No_;
			}
			set
			{
				if ((this._No_ != value))
				{
					this.OnNo_Changing(value);
					this.SendPropertyChanging();
					this._No_ = value;
					this.SendPropertyChanged("No_");
					this.OnNo_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(250) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attachment", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Attachment
		{
			get
			{
				return this._Attachment;
			}
			set
			{
				if ((this._Attachment != value))
				{
					this.OnAttachmentChanging(value);
					this.SendPropertyChanging();
					this._Attachment = value;
					this.SendPropertyChanged("Attachment");
					this.OnAttachmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[No_ Series]", Storage="_No__Series", DbType="NVarChar(10) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string No__Series
		{
			get
			{
				return this._No__Series;
			}
			set
			{
				if ((this._No__Series != value))
				{
					this.OnNo__SeriesChanging(value);
					this.SendPropertyChanging();
					this._No__Series = value;
					this.SendPropertyChanged("No__Series");
					this.OnNo__SeriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Created By]", Storage="_Created_By", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Created_By
		{
			get
			{
				return this._Created_By;
			}
			set
			{
				if ((this._Created_By != value))
				{
					this.OnCreated_ByChanging(value);
					this.SendPropertyChanging();
					this._Created_By = value;
					this.SendPropertyChanged("Created_By");
					this.OnCreated_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date Created]", Storage="_Date_Created", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Date_Created
		{
			get
			{
				return this._Date_Created;
			}
			set
			{
				if ((this._Date_Created != value))
				{
					this.OnDate_CreatedChanging(value);
					this.SendPropertyChanging();
					this._Date_Created = value;
					this.SendPropertyChanged("Date_Created");
					this.OnDate_CreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Modified]", Storage="_Last_Modified", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Last_Modified
		{
			get
			{
				return this._Last_Modified;
			}
			set
			{
				if ((this._Last_Modified != value))
				{
					this.OnLast_ModifiedChanging(value);
					this.SendPropertyChanging();
					this._Last_Modified = value;
					this.SendPropertyChanged("Last_Modified");
					this.OnLast_ModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Modified By]", Storage="_Last_Modified_By", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Last_Modified_By
		{
			get
			{
				return this._Last_Modified_By;
			}
			set
			{
				if ((this._Last_Modified_By != value))
				{
					this.OnLast_Modified_ByChanging(value);
					this.SendPropertyChanging();
					this._Last_Modified_By = value;
					this.SendPropertyChanged("Last_Modified_By");
					this.OnLast_Modified_ByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Transferred to Dest_]", Storage="_Transferred_to_Dest_", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte Transferred_to_Dest_
		{
			get
			{
				return this._Transferred_to_Dest_;
			}
			set
			{
				if ((this._Transferred_to_Dest_ != value))
				{
					this.OnTransferred_to_Dest_Changing(value);
					this.SendPropertyChanging();
					this._Transferred_to_Dest_ = value;
					this.SendPropertyChanged("Transferred_to_Dest_");
					this.OnTransferred_to_Dest_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Comptroller$Change Log Entry]")]
	public partial class Comptroller_Change_Log_Entry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Data.Linq.Binary _timestamp;
		
		private long _Entry_No_;
		
		private System.DateTime _Date_and_Time;
		
		private System.DateTime _Time;
		
		private string _User_ID;
		
		private int _Table_No_;
		
		private int _Field_No_;
		
		private int _Type_of_Change;
		
		private string _Old_Value;
		
		private string _New_Value;
		
		private string _Primary_Key;
		
		private int _Primary_Key_Field_1_No_;
		
		private string _Primary_Key_Field_1_Value;
		
		private int _Primary_Key_Field_2_No_;
		
		private string _Primary_Key_Field_2_Value;
		
		private int _Primary_Key_Field_3_No_;
		
		private string _Primary_Key_Field_3_Value;
		
		private System.Data.Linq.Binary _Record_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntimestampChanging(System.Data.Linq.Binary value);
    partial void OntimestampChanged();
    partial void OnEntry_No_Changing(long value);
    partial void OnEntry_No_Changed();
    partial void OnDate_and_TimeChanging(System.DateTime value);
    partial void OnDate_and_TimeChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    partial void OnUser_IDChanging(string value);
    partial void OnUser_IDChanged();
    partial void OnTable_No_Changing(int value);
    partial void OnTable_No_Changed();
    partial void OnField_No_Changing(int value);
    partial void OnField_No_Changed();
    partial void OnType_of_ChangeChanging(int value);
    partial void OnType_of_ChangeChanged();
    partial void OnOld_ValueChanging(string value);
    partial void OnOld_ValueChanged();
    partial void OnNew_ValueChanging(string value);
    partial void OnNew_ValueChanged();
    partial void OnPrimary_KeyChanging(string value);
    partial void OnPrimary_KeyChanged();
    partial void OnPrimary_Key_Field_1_No_Changing(int value);
    partial void OnPrimary_Key_Field_1_No_Changed();
    partial void OnPrimary_Key_Field_1_ValueChanging(string value);
    partial void OnPrimary_Key_Field_1_ValueChanged();
    partial void OnPrimary_Key_Field_2_No_Changing(int value);
    partial void OnPrimary_Key_Field_2_No_Changed();
    partial void OnPrimary_Key_Field_2_ValueChanging(string value);
    partial void OnPrimary_Key_Field_2_ValueChanged();
    partial void OnPrimary_Key_Field_3_No_Changing(int value);
    partial void OnPrimary_Key_Field_3_No_Changed();
    partial void OnPrimary_Key_Field_3_ValueChanging(string value);
    partial void OnPrimary_Key_Field_3_ValueChanged();
    partial void OnRecord_IDChanging(System.Data.Linq.Binary value);
    partial void OnRecord_IDChanged();
    #endregion
		
		public Comptroller_Change_Log_Entry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Entry No_]", Storage="_Entry_No_", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long Entry_No_
		{
			get
			{
				return this._Entry_No_;
			}
			set
			{
				if ((this._Entry_No_ != value))
				{
					this.OnEntry_No_Changing(value);
					this.SendPropertyChanging();
					this._Entry_No_ = value;
					this.SendPropertyChanged("Entry_No_");
					this.OnEntry_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date and Time]", Storage="_Date_and_Time", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Date_and_Time
		{
			get
			{
				return this._Date_and_Time;
			}
			set
			{
				if ((this._Date_and_Time != value))
				{
					this.OnDate_and_TimeChanging(value);
					this.SendPropertyChanging();
					this._Date_and_Time = value;
					this.SendPropertyChanged("Date_and_Time");
					this.OnDate_and_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User ID]", Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Table No_]", Storage="_Table_No_", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Table_No_
		{
			get
			{
				return this._Table_No_;
			}
			set
			{
				if ((this._Table_No_ != value))
				{
					this.OnTable_No_Changing(value);
					this.SendPropertyChanging();
					this._Table_No_ = value;
					this.SendPropertyChanged("Table_No_");
					this.OnTable_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Field No_]", Storage="_Field_No_", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Field_No_
		{
			get
			{
				return this._Field_No_;
			}
			set
			{
				if ((this._Field_No_ != value))
				{
					this.OnField_No_Changing(value);
					this.SendPropertyChanging();
					this._Field_No_ = value;
					this.SendPropertyChanged("Field_No_");
					this.OnField_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Type of Change]", Storage="_Type_of_Change", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Type_of_Change
		{
			get
			{
				return this._Type_of_Change;
			}
			set
			{
				if ((this._Type_of_Change != value))
				{
					this.OnType_of_ChangeChanging(value);
					this.SendPropertyChanging();
					this._Type_of_Change = value;
					this.SendPropertyChanged("Type_of_Change");
					this.OnType_of_ChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Old Value]", Storage="_Old_Value", DbType="NVarChar(250) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Old_Value
		{
			get
			{
				return this._Old_Value;
			}
			set
			{
				if ((this._Old_Value != value))
				{
					this.OnOld_ValueChanging(value);
					this.SendPropertyChanging();
					this._Old_Value = value;
					this.SendPropertyChanged("Old_Value");
					this.OnOld_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[New Value]", Storage="_New_Value", DbType="NVarChar(250) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string New_Value
		{
			get
			{
				return this._New_Value;
			}
			set
			{
				if ((this._New_Value != value))
				{
					this.OnNew_ValueChanging(value);
					this.SendPropertyChanging();
					this._New_Value = value;
					this.SendPropertyChanged("New_Value");
					this.OnNew_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key]", Storage="_Primary_Key", DbType="NVarChar(250) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Primary_Key
		{
			get
			{
				return this._Primary_Key;
			}
			set
			{
				if ((this._Primary_Key != value))
				{
					this.OnPrimary_KeyChanging(value);
					this.SendPropertyChanging();
					this._Primary_Key = value;
					this.SendPropertyChanged("Primary_Key");
					this.OnPrimary_KeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key Field 1 No_]", Storage="_Primary_Key_Field_1_No_", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Primary_Key_Field_1_No_
		{
			get
			{
				return this._Primary_Key_Field_1_No_;
			}
			set
			{
				if ((this._Primary_Key_Field_1_No_ != value))
				{
					this.OnPrimary_Key_Field_1_No_Changing(value);
					this.SendPropertyChanging();
					this._Primary_Key_Field_1_No_ = value;
					this.SendPropertyChanged("Primary_Key_Field_1_No_");
					this.OnPrimary_Key_Field_1_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key Field 1 Value]", Storage="_Primary_Key_Field_1_Value", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Primary_Key_Field_1_Value
		{
			get
			{
				return this._Primary_Key_Field_1_Value;
			}
			set
			{
				if ((this._Primary_Key_Field_1_Value != value))
				{
					this.OnPrimary_Key_Field_1_ValueChanging(value);
					this.SendPropertyChanging();
					this._Primary_Key_Field_1_Value = value;
					this.SendPropertyChanged("Primary_Key_Field_1_Value");
					this.OnPrimary_Key_Field_1_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key Field 2 No_]", Storage="_Primary_Key_Field_2_No_", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Primary_Key_Field_2_No_
		{
			get
			{
				return this._Primary_Key_Field_2_No_;
			}
			set
			{
				if ((this._Primary_Key_Field_2_No_ != value))
				{
					this.OnPrimary_Key_Field_2_No_Changing(value);
					this.SendPropertyChanging();
					this._Primary_Key_Field_2_No_ = value;
					this.SendPropertyChanged("Primary_Key_Field_2_No_");
					this.OnPrimary_Key_Field_2_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key Field 2 Value]", Storage="_Primary_Key_Field_2_Value", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Primary_Key_Field_2_Value
		{
			get
			{
				return this._Primary_Key_Field_2_Value;
			}
			set
			{
				if ((this._Primary_Key_Field_2_Value != value))
				{
					this.OnPrimary_Key_Field_2_ValueChanging(value);
					this.SendPropertyChanging();
					this._Primary_Key_Field_2_Value = value;
					this.SendPropertyChanged("Primary_Key_Field_2_Value");
					this.OnPrimary_Key_Field_2_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key Field 3 No_]", Storage="_Primary_Key_Field_3_No_", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Primary_Key_Field_3_No_
		{
			get
			{
				return this._Primary_Key_Field_3_No_;
			}
			set
			{
				if ((this._Primary_Key_Field_3_No_ != value))
				{
					this.OnPrimary_Key_Field_3_No_Changing(value);
					this.SendPropertyChanging();
					this._Primary_Key_Field_3_No_ = value;
					this.SendPropertyChanged("Primary_Key_Field_3_No_");
					this.OnPrimary_Key_Field_3_No_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Key Field 3 Value]", Storage="_Primary_Key_Field_3_Value", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Primary_Key_Field_3_Value
		{
			get
			{
				return this._Primary_Key_Field_3_Value;
			}
			set
			{
				if ((this._Primary_Key_Field_3_Value != value))
				{
					this.OnPrimary_Key_Field_3_ValueChanging(value);
					this.SendPropertyChanging();
					this._Primary_Key_Field_3_Value = value;
					this.SendPropertyChanged("Primary_Key_Field_3_Value");
					this.OnPrimary_Key_Field_3_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Record ID]", Storage="_Record_ID", DbType="VarBinary(448) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Record_ID
		{
			get
			{
				return this._Record_ID;
			}
			set
			{
				if ((this._Record_ID != value))
				{
					this.OnRecord_IDChanging(value);
					this.SendPropertyChanging();
					this._Record_ID = value;
					this.SendPropertyChanged("Record_ID");
					this.OnRecord_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
